/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Governance } from "./Governance";
export type { GovernanceToken } from "./GovernanceToken";

export { Governance__factory } from "./factories/Governance__factory";
export { GovernanceToken__factory } from "./factories/GovernanceToken__factory";
